---
- name: Webserver setup
  hosts: webservers
  # Sudo
  become: yes
  tasks: 
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start&Enabled httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes    
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks: 
    - name: Install Mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start&Enabled Mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes  