version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
   runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq 
      # install maven
      # - wget https://archive.apache.org/dist/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
      - aws s3 cp s3://your-bucket-name/tools/apache-maven-3.9.8-bin.tar.gz .
      - tar xzf apache-maven-3.9.8-bin.tar.gz
      - ln -s apache-maven-3.9.8 maven
      ## change the password, username of RDS admin
      - sed -i 's/jdbc.password=(password)/jdbc.password=(changed password)/' src/main/resources/application.properties
      - sed -i 's/jdbc.username=(username)/jdbc.username=(changed username)/' src/main/resources/application.properties
      - sed -i 's/db01:3306/(rds endpoint):3306/' src/main/resources/application.properties
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mvn package
artifacts:
  files:
     - '**/*'
  base-directory: 'target/vprofile-v2'