--- 
  # We did not have a remote machine yet
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair
      ec2_key:
        name: ansible-playbook-keypair
        region: us-east-1
      register: keyout
    
  # - name: Print key pair
    # debug:
      # var: keyout

    - name: Save key pair
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./ansible-playbook-keypair.pem
      when: keyout.changed

    - name: Start an instance
      amazon.aws.ec2_instance:
        name: "ansible-instance"
        key_name: "ansible-playbook-keypair"
        # Use default vpc
        # vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        # network_interfaces:
          # - assign_public_ip: true
        # Amazon Linux from us-east-1
        image_id: ami-0953476d60561c955
        region: us-east-1
        # It we do not metion this and we run it multiple times, it will create mutiple instance
        exact_count: 1
        tags:
          Environment: Testing