# Global values
nameOverride: ""
fullnameOverride: ""

# WordPress configuration
wordpress:
  image:
    repository: wordpress
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  persistence:
    enabled: true
    storageClass: "default"
    size: 3Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
# MySQL configuration
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  persistence:
    enabled: true
    storageClass: "default"
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  host: wordpress.agsfva.online
  tls: []

# Secret configuration
# this is for practicing helm
# Do NOT expose secret like this
secret:
  mysqlRootPassword: "rootpassword"
  mysqlPassword: "wordpresspass"
  mysqlDatabase: "wordpress"
  mysqlUser: "wordpress"