#SPDX-License-Identifier: MIT-0
---
# handlers file for post-install
- name: Restart chronyd service on CentOS
  service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Restart ntp service on Ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
