pipeline {
  agent any
  // This env come from -> Manage Jenkins -> Credentials
  environment {
    REPO_URL = credentials('hkh-repo-url')
  }
  tools {
    maven : "MAVEN3.9"
    jdk "JDK17"
  }

  stages {
    stage('Fetch code') {
      steps {
        // git option: ' ', option: ' ', .....
        git branch: 'atom', url: "${env.REPO_URL}"
      }
    }

    stage('Unit Test') {
      steps {
        // sh for shell command sh '(command)'
        sh 'mvn test'
      }
    }

    stage('Build') {
      steps {
        // skip the test from previos step
        sh 'mvn install -DskipTests'
      }
      // post build
      post {
        success {
          echo "Archiving Artifact"
          archiveArtifacts artifacts: '**/*.war'
        }
      }
    }
  }
}