---
- name: Provisioning server 
  hosts: all
  become: yes
  tasks:
    - name: Install with Loop on CentOS
      yum: 
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install ntp agent on Ubuntu
      apt: 
        name: "{{item.service}}"
        state: "{{item.state}}"
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - { service: "ntp", state: "present" }
        - { service: "wget", state: "present" }
        - { service: "git", state: "present" }
        - { service: "zip", state: "present" }
        - { service: "unzip", state: "present" }

    - name: Start chronyd service on CentOS
      service: 
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"   
    
    - name: Start ntp service on Ubuntu
      service: 
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    # Create Announment file on motd(Message of the Day)
    - name: Banner file
      copy:
        # Copy this text into the destination
        content: "# This server is managed by ansible. No manual changes"
        dest: /etc/motd
    
    - name: Create a directory
      file: 
        path: /opt/test21
        state: directory

    # Create our own configuretion
    - name: Deploy ntp agent conf on CentOS
      # template can pass variable in conf file
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      ## Noti the handlers
      notify:
        ## must be the exactly name
        - Restart chronyd service on CentOS

    - name: Deploy ntp agent conf on Ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
      ## Noti this too
      notify:
        - Restart ntp service on Ubuntu
        
  ## tasks in handlers will execute after they got notify from the above tasks
  handlers:
    - name: Restart chronyd service on CentOS
      service: 
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"   
    
    - name: Restart ntp service on Ubuntu
      service: 
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"

