apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 3Gi
  storageClassName: default