---
- name: Print facts
  ## gather_facts: False
  hosts: all
  tasks:
      ## print some information in target machine by using variable in gather_facts
    - name: Print OS name
      debug:
        var: ansible_distribution
    - name: Print selinux mode
      debug:
        var: ansible_selinux.mode     
    - name: Print RAM memory
      debug:
        var: ansible_memory_mb.real.free
    - name: Print Processor name
      debug:
        var: ansible_processor[2]