#SPDX-License-Identifier: MIT-0
---
# tasks file for post-install
- name: Install with Loop on CentOS
  yum:
    name: "{{item}}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip

- name: Install ntp agent on Ubuntu
  apt:
    name: "{{item.service}}"
    state: "{{item.state}}"
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - { service: "ntp", state: "present" }
    - { service: "wget", state: "present" }
    - { service: "git", state: "present" }
    - { service: "zip", state: "present" }
    - { service: "unzip", state: "present" }

- name: Start chronyd service on CentOS
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Start ntp service on Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: "# This server is managed by ansible. No manual changes"
    dest: /etc/motd

- name: Create a directory
  file:
    path: /opt/test21
    state: directory

- name: Deploy ntp agent conf on CentOS
  template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - Restart chronyd service on CentOS

- name: Deploy ntp agent conf on Ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - Restart ntp service on Ubuntu

- name: Create a folder
  file:
    path: "{{dump_dir}}"
    state: directory

- name: Dump files
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt
