---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    # key and value should be the same as template label
    matchLabels:
      tier: frontend
  template:
    metadata:
      # this must be the same as you metion on matchLabels
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5