---
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    # command that will execute in container
    command: ["printenv"]
    # arguments
    args: ["HOSTNAME", "KUBERNETES_PORT"]
    
  restartPolicy: OnFailure
  
# when you run this it will get the result like this
# kubectl logs command-demo
# command-demo
# tcp://100.64.0.1:443